project_name: curlie
builds:
  -
    binary: curlie
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - freebsd
      - windows
    goarch:
      - amd64
      - arm
      - arm64
release:
  name_template: "{{.ProjectName}}-v{{.Version}}"
brews:
  -
    tap:
      owner: rs
      name: homebrew-tap
    commit_author:
      name: Olivier Poitrey
      email: rs@rhapsodyk.net
    homepage: https://curlie.io
    description: The power of curl, the ease of use of httpie.
nfpms:
  -
    maintainer: Olivier Poitrey <rs@rhapsodyk.net>
    description: curle is a frontend to curl that offers the ease of use of httpie without having to compromise curl features and performance.
    license: MIT
    formats:
      - deb
      - rpm
    dependencies:
      - curl
    bindir: /usr/bin
