project_name: curlie
builds:
  -
    binary: curlie
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - freebsd
      - windows
release:
  name_template: "{{.ProjectName}}-v{{.Version}}"
git:
  short_hash: true
brew:
  github:
    owner: rs
    name: homebrew-tap
  commit_author:
    name: Olivier Poitrey
    email: rs@rhapsodyk.net
  homepage: https://github.com/rs/curlie
  description: The power of curl, the ease of use of httpie.
nfpm:
  maintainer: Olivier Poitrey <rs@rhapsodyk.net>
  description: curle is a frontend to curl that offers the ease of use of httpie without having to compromise curl features and performance.
  license: MIT
  formats:
    - deb
    - rpm
  dependencies:
    - curl
  bindir: /usr/bin
