version: 2
project_name: curlie
builds:
  - binary: curlie
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - freebsd
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - ppc64le
      - s390x
    goarm:
      - 6
      - 7

archives:
  - format_overrides:
      - goos: windows
        formats: ['zip']

release:
  name_template: "{{.ProjectName}}-v{{.Version}}"

signs:
  - cmd: cosign
    artifacts: checksum
    output: true
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--output-signature=${signature}"
      - "--output-certificate=${certificate}"
      - "${artifact}"
      - "--yes"

brews:
  - repository:
      owner: rs
      name: homebrew-tap
    commit_author:
      name: Olivier Poitrey
      email: rs@rhapsodyk.net
    homepage: https://github.com/rs/curlie
    description: The power of curl, the ease of use of httpie.

nfpms:
  - maintainer: Olivier Poitrey <rs@rhapsodyk.net>
    description: curle is a frontend to curl that offers the ease of use of httpie without having to compromise curl features and performance.
    license: MIT
    formats:
      - deb
      - rpm
    dependencies:
      - curl
    bindir: /usr/bin
